site_name: pyCuSAXS Documentation
site_url: https://octupole.github.io/pyCuSaxs/
site_author: pyCuSAXS Authors
site_description: >-
  GPU-accelerated SAXS analysis for molecular dynamics trajectories.
  High-performance CUDA backend with Python tooling for GROMACS simulations.

repo_name: octupole/pyCuSaxs
repo_url: https://github.com/octupole/pyCuSaxs
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 pyCuSAXS Authors

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/octupole/pyCuSaxs
  version:
    provider: mike
    default: latest

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Command Line: user-guide/cli.md
    - Graphical Interface: user-guide/gui.md
    - Database Management: user-guide/database.md
    - Solvent Subtraction: user-guide/solvent-subtraction.md
    - Python API: user-guide/python-api.md
  - Algorithm:
    - Overview: algorithm/overview.md
    - Pipeline: algorithm/pipeline.md
    - Performance: algorithm/performance.md
  - API Reference:
    - Backend (C++/CUDA): api/backend.md
    - Python: api/python.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Bug Fixes: development/changelog.md
  - Troubleshooting: troubleshooting.md
